name: Workflow for Python-CI

on:
 pull_request:

jobs:
  python-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Test with Pytest
        run: |
          pip3 install coverage
          pwd && ls -la
          python3 -m coverage run -m unittest src/main/python/helloworld.py 
          python3 -m coverage report
          python3 -m coverage html
          python3 -m coverage xml
          pwd && ls -la
          
          
      - name: Request Changes
        if: failure()
        uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
             gh api repos/pooja03ydv/python-app/branches/smita/protection/required_status_checks/contexts -X POST -F contexts[]=unit-tests
             gh pr comment ${{ github.event.pull_request.number }} --body "Unit tests failed. Please fix the issues before merging."
             gh pr status -b ${{ github.event.pull_request.number }} -s "Changes requested"
          
      - name: Reject pull request on test failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              curl -X POST \
                   -H "Authorization: token <your_personal_access_token>" \
                   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/pooja03ydv/python-app/pulls/${{ github.event.pull_request.number }}/reviews \
                   -d '{"commit_id": "HEAD", "event": "REQUEST_CHANGES", "body": "Unit tests failed"}'


     
          
      - name: Delete pull request on test failure
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ secrets.token}}
        run: |
      
          gh pr comment ${{ github.event.pull_request.number }} --body "Test results:<br/>$(cat /home/runner/work/python-app/python-app/coverage.xml)"
          gh pr comment ${{ github.event.pull_request.number }} --body "Test results:<br/>$(cat /home/runner/work/python-app/python-app/htmlcov/index.html)"
          
         

          
      
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
